[package]
authors = ["7hoenix <jpholzmann@gmail.com>"]
edition = "2018"
name = "client"
version = "0.1.0"

[dependencies]
common = { path = "../common" }
serde = "1.0"
serde_json = "1.0.56"
structopt = "0.3"
tokio-util = "0.3.1"
