[package]
name = "proxy"
version = "0.1.0"
authors = ["7hoenix <jpholzmann@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.21", features = ["macros"] }
hyper = "0.13.6"
hyper-tls = "0.4.1"
